# Generated by Django 2.0.2 on 2018-03-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('network', '0001_squashed_0082_auto_20180725_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='L2_SERVICES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpls', models.IntegerField(unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.CLIENTS')),
                ('sap', models.ManyToManyField(to='network.SAP')),
            ],
        ),
        migrations.CreateModel(
            name='SHG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vpls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l2.L2_SERVICES')),
            ],
        ),
    ]
