# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipoe_servicess',
            options={'ordering': ['client', 'sap'], 'verbose_name': 'Услуга IPoE', 'verbose_name_plural': 'Услуги IPoE'},
        ),
    ]
