"""
Django settings for guts project.

Generated by 'django-admin startproject' using Django 1.11.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9#)=9nl5ibw)uogfb_#*5avkt#agz7pmz4(8_^^%zg5kq^_lw('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
                 "127.0.0.1",
                 "irk-cus.cf",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'network.apps.NetworkConfig',
    'clients.apps.ClientsConfig',
    'ipoe.apps.IpoeConfig',
    'l2.apps.L2Config',
    'registration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'guts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates',
            os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'guts_2.0',
        'USER': 'root',
        'PASSWORD': 'Per$pektiv@',
        'HOST': '127.0.0.1',
#        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Irkutsk'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(BASE_DIR, 'files', 'media')
MEDIA_URL = '/media/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.ilam.cf'
DEFAULT_FROM_EMAIL = 'ilam@ilam.cf'
EMAIL_PORT = '25'
EMAIL_HOST_USER = 'guts@ilam.cf'
EMAIL_HOST_PASSWORD = 'K0l0tundr@351'

ACCOUNT_ACTIVATION_DAYS = 2

# Тип подключения на порту коммутатора доступа
CONNECTION_TYPES = (
    (0  , 'Магистральный порт'),
    (1  , 'Распределительный порт'),
    (3  , 'PPPoE-подключение'),
    (4  , 'Прочее-подключение'),
    (5  , 'Сигнализатор'),
    (99 , 'Неисправный порт')
)
GUTS_CONSTANTS = {
    'SNMP_CONTACT'      : 'ER-Telecom',
    'TFTP_IP_LOCAL'     : '10.111.31.11',
    'TFTP_IP_REMOTE'    : '109.194.16.10',
    'EQM_IP'            : '109.194.16.25',
    'ADMIN_PROXY_IP'    : '109.194.16.10',
    'NS2_IP'            : '109.194.16.4',
    'NS4_IP'            : '109.194.17.5',
    'RADIUS1_IP'        : '109.194.16.37',
    'RADIUS2_IP'        : '109.194.16.38',
    'radius_port'       : '2030',
    'acct_port'         : '2050',
    'radius_key'        : '9rsrLWBnOJaA',
    'TIME_ZONE'         : '8',
    'SNMP_RW_COMMUNITY' : 'rWIrkuz',
    'MGMT_VLAN'         : '99',
    'PERMANENT_VLANS'    : '1001-1025,1051-1075,1101-1125,1151-1175,1201-1225,1251-1275,1301-1325,1351-1375,1401-1425,1451-1475,1501-1525,1551-1575,1601-1625'
}
