# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import network.models


class Migration(migrations.Migration):

    replaces = [('network', '0001_initial'), ('network', '0002_auto_20180303_1240'), ('network', '0003_auto_20180305_0901'), ('network', '0004_auto_20180305_0924'), ('network', '0005_auto_20180305_1000'), ('network', '0006_auto_20180305_1009'), ('network', '0007_auto_20180305_1014'), ('network', '0008_vlan'), ('network', '0009_auto_20180309_0804'), ('network', '0010_auto_20180309_0808'), ('network', '0011_auto_20180309_0820'), ('network', '0012_auto_20180309_1015'), ('network', '0013_auto_20180309_1106'), ('network', '0014_auto_20180309_1115'), ('network', '0015_auto_20180309_1224'), ('network', '0016_auto_20180309_1225'), ('network', '0017_auto_20180309_1236'), ('network', '0018_auto_20180309_1352'), ('network', '0019_auto_20180309_1556'), ('network', '0020_thread_num_in_campus'), ('network', '0021_auto_20180314_0506'), ('network', '0022_mgs_mgs_num'), ('network', '0023_auto_20180323_0541'), ('network', '0024_auto_20180323_0716'), ('network', '0025_auto_20180323_1258'), ('network', '0026_auto_20180323_1319'), ('network', '0027_auto_20180323_1328'), ('network', '0028_auto_20180323_1329'), ('network', '0029_auto_20180323_1331'), ('network', '0030_auto_20180323_1339'), ('network', '0031_auto_20180325_0745'), ('network', '0032_auto_20180325_1049'), ('network', '0033_auto_20180326_0636'), ('network', '0034_auto_20180326_0638'), ('network', '0035_auto_20180404_0834'), ('network', '0036_auto_20180404_0842'), ('network', '0037_auto_20180405_0701'), ('network', '0038_auto_20180406_0053'), ('network', '0039_port_type'), ('network', '0040_auto_20180414_1420'), ('network', '0041_auto_20180414_1426'), ('network', '0042_auto_20180414_1507'), ('network', '0043_auto_20180414_1628'), ('network', '0044_auto_20180414_1645'), ('network', '0045_auto_20180415_0422'), ('network', '0046_auto_20180415_0517'), ('network', '0047_port_type_is_bad'), ('network', '0048_auto_20180415_0524'), ('network', '0049_auto_20180415_0544'), ('network', '0050_auto_20180415_0545'), ('network', '0051_auto_20180415_0603'), ('network', '0052_auto_20180415_1103'), ('network', '0053_remove_port_of_access_switch_type'), ('network', '0054_auto_20180415_1241'), ('network', '0055_auto_20180415_1302'), ('network', '0056_sw_model_ports_names'), ('network', '0057_auto_20180605_0955'), ('network', '0058_port_of_access_switch_port_name'), ('network', '0059_auto_20180607_1444'), ('network', '0060_auto_20180607_1511'), ('network', '0061_auto_20180614_1015'), ('network', '0062_auto_20180614_1015'), ('network', '0063_auto_20180614_1143'), ('network', '0064_auto_20180619_1351'), ('network', '0065_auto_20180619_1424'), ('network', '0066_auto_20180619_1427'), ('network', '0067_auto_20180619_1429'), ('network', '0068_delete_vlan'), ('network', '0069_access_switch_gw'), ('network', '0070_access_switch_subnet'), ('network', '0071_auto_20180622_0813'), ('network', '0072_auto_20180622_0814'), ('network', '0073_auto_20180622_0832'), ('network', '0074_auto_20180622_1343'), ('network', '0075_auto_20180623_0615'), ('network', '0076_remove_access_switch_subnet'), ('network', '0077_sw_model_fw_file'), ('network', '0078_sw_model_fw_update_commands'), ('network', '0079_auto_20180719_1226'), ('network', '0080_sw_model_eqm_type'), ('network', '0081_auto_20180725_1627'), ('network', '0082_auto_20180725_1706')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('lag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.LAG')),
                ('mgs_num', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name_plural': 'МГС',
                'verbose_name': 'МГС',
            },
        ),
        migrations.CreateModel(
            name='ACCESS_NODE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ACCESS_SWITCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ports_count', models.IntegerField(default=0)),
                ('ports_types', models.CharField(blank=True, max_length=100)),
                ('u_vlans', models.CharField(blank=True, max_length=500)),
                ('t_vlans', models.CharField(blank=True, max_length=500)),
                ('access_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.ACCESS_NODE')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.IP_ADDRESS')),
            ],
        ),
        migrations.CreateModel(
            name='CAMPUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SUBNET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=15)),
                ('mask', models.IntegerField(default=28)),
                ('hostmin', models.CharField(max_length=15)),
                ('hosmax', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SW_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.VENDORS', verbose_name='Производитель')),
                ('title', models.CharField(max_length=100, verbose_name='Название модели')),
                ('fw_version', models.CharField(blank=True, max_length=100, verbose_name='Рекомендованная версия ПО')),
                ('hw_version', models.CharField(blank=True, max_length=100, verbose_name='HW версия')),
                ('ports_count', models.IntegerField(default=0, verbose_name='Количество портов')),
                ('ports_types', models.CharField(blank=True, help_text='0-Магистральный порт, 1-Распределительный порт, 3-PPPoE-подключение, 4-Прочее-подключение, 5-Сигнализатор, 99-Неисправный порт', max_length=200, verbose_name='Типы портов по умолчанию')),
                ('cfg_template', models.CharField(blank=True, max_length=100)),
                ('ports_names', models.CharField(blank=True, max_length=500, verbose_name='Названия портов в конфиге')),
                ('fw_file', models.CharField(blank=True, max_length=100, verbose_name='Файл прошивки')),
                ('fw_update_commands', models.TextField(blank=True, verbose_name='Описание процесса обновления прошивки')),
                ('cfg_download_commands', models.TextField(blank=True, verbose_name='Описание процесса загрузки конфигурации')),
                ('eqm_type', models.CharField(default='', max_length=100, verbose_name='Тип объекта в eqm')),
            ],
            options={
                'ordering': ['vendor', 'title'],
                'verbose_name_plural': 'Модели коммутаторов',
                'verbose_name': 'Модель коммутаторов',
            },
        ),
        migrations.CreateModel(
            name='THREAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outvlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outvlan', to='network.VLAN')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.CAMPUS')),
                ('mapvlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapvlan', to='network.VLAN')),
                ('num_in_campus', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Нитки',
                'verbose_name': 'Нитка',
            },
        ),
        migrations.AddField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
        migrations.AddField(
            model_name='campus',
            name='mgs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MGS'),
        ),
        migrations.AddField(
            model_name='access_switch',
            name='sw_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.SW_MODEL'),
        ),
        migrations.AddField(
            model_name='access_node',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
        migrations.CreateModel(
            name='LAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('s_vlan', models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='SVID')),
                ('c_vlan', models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='CVID')),
                ('lag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.LAG')),
            ],
            options={
                'ordering': ['lag', 's_vlan', 'c_vlan'],
            },
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['title'], 'verbose_name': 'Кампус', 'verbose_name_plural': 'Кампусы'},
        ),
        migrations.AlterModelOptions(
            name='subnet',
            options={'verbose_name': 'Подсеть', 'verbose_name_plural': 'Подсети'},
        ),
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='access_switch',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.SUBNET'),
        ),
        migrations.AlterField(
            model_name='access_switch',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='hosmax',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='hostmin',
        ),
        migrations.CreateModel(
            name='VENDORS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Вендоры',
                'verbose_name': 'Вендор',
            },
        ),
        migrations.AlterModelOptions(
            name='access_node',
            options={'verbose_name': 'Узел доступа', 'verbose_name_plural': 'Узлы доступа'},
        ),
        migrations.AlterModelOptions(
            name='access_switch',
            options={'verbose_name': 'Коммутатор доступа', 'verbose_name_plural': 'Коммутаторы доступа'},
        ),
        migrations.AlterField(
            model_name='access_switch',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set([('campus', 'num_in_campus')]),
        ),
        migrations.AlterField(
            model_name='campus',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='campus',
            name='mgs',
        ),
        migrations.AlterField(
            model_name='campus',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_in_mgs', models.IntegerField(default=1)),
                ('mgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MGS', verbose_name='Магистраль')),
            ],
            options={
                'verbose_name_plural': 'Магистрали',
                'verbose_name': 'Магистраль',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ms',
            unique_together=set([('mgs', 'num_in_mgs')]),
        ),
        migrations.AddField(
            model_name='campus',
            name='ms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MS', verbose_name='МС'),
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['ms', 'num_in_ms'], 'verbose_name': 'Кампус', 'verbose_name_plural': 'Кампусы'},
        ),
        migrations.AddField(
            model_name='campus',
            name='num_in_ms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together=set([('ms', 'num_in_ms')]),
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ('ms', 'num_in_ms'), 'verbose_name': 'Кампус', 'verbose_name_plural': 'Кампусы'},
        ),
        migrations.RemoveField(
            model_name='campus',
            name='title',
        ),
        migrations.AddField(
            model_name='campus',
            name='prefix',
            field=models.CharField(choices=[('ppk', 'ППК'), ('mku', 'МКУ')], default='ppk', max_length=20, verbose_name='Префикс'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='mgs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MGS', verbose_name='МГС'),
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='mask',
        ),
        migrations.AlterField(
            model_name='ms',
            name='num_in_mgs',
            field=models.IntegerField(default=1, verbose_name='Номер магистрали в МГС'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.THREAD'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.CharField(max_length=18),
        ),
        migrations.CreateModel(
            name='GUTS_NETWORK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=18, unique=True, validators=[network.models.validator_net_addr])),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['description'],
                'verbose_name_plural': 'Подсети разрешонные в ГУТС.',
                'verbose_name': 'Подсеть',
            },
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['campus', 'num_in_campus'], 'verbose_name': 'Нитка', 'verbose_name_plural': 'Нитки'},
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='subnet',
        ),
        migrations.AlterField(
            model_name='access_node',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PORT_TYPE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Описание типа порта')),
                ('default_description', models.CharField(blank=True, max_length=200, verbose_name='Название порта поумолчанию')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Цвет типа порта.')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Типы портов',
                'verbose_name': 'Тип порта',
            },
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='ports_types',
        ),
        migrations.CreateModel(
            name='PORT_OF_ACCESS_SWITCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_in_switch', models.IntegerField(default=0, editable=False)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('u_vlan', models.CharField(blank=True, max_length=100)),
                ('t_vlans', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='ports_count',
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='access_switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.ACCESS_SWITCH'),
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.PORT_TYPE'),
        ),
        migrations.AlterModelOptions(
            name='port_of_access_switch',
            options={'ordering': ['access_switch', 'num_in_switch'], 'verbose_name': 'Порт коммутатора доступа', 'verbose_name_plural': 'Порты коммутаторов доступа'},
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='t_vlans',
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='u_vlans',
        ),
        migrations.AlterField(
            model_name='port_of_access_switch',
            name='u_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.VLAN', verbose_name='Untag-vlan/PVID'),
        ),
        migrations.AlterField(
            model_name='port_of_access_switch',
            name='u_vlan',
            field=models.IntegerField(default=0, verbose_name='Untag-vlan/PVID'),
        ),
        migrations.RemoveField(
            model_name='port_of_access_switch',
            name='type',
        ),
        migrations.AlterField(
            model_name='port_of_access_switch',
            name='num_in_switch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='port_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='port_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.PORT_TYPE'),
        ),
        migrations.AlterField(
            model_name='port_of_access_switch',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='port_of_access_switch',
            unique_together=set([('access_switch', 'num_in_switch')]),
        ),
        migrations.AlterField(
            model_name='thread',
            name='outvlan',
            field=models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='Внешний vlan'),
        ),
        migrations.AlterUniqueTogether(
            name='sap',
            unique_together=set([('lag', 's_vlan', 'c_vlan')]),
        ),
        migrations.AlterField(
            model_name='thread',
            name='mapvlan',
            field=models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='Внешний vlan'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='mapvlan',
            field=models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='Map-vlan'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='gw',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4', verbose_name='Адрес шлюза'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.CharField(max_length=18, unique=True, verbose_name='Подсеть'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD', verbose_name='Нитка'),
        ),
        migrations.AddField(
            model_name='access_switch',
            name='cfg_file',
            field=models.CharField(blank=True, help_text='Значение поля очищается при каждых изменениях коммутатора', max_length=200, verbose_name='Файл текущей конфигурации.'),
        ),
    ]
