# Generated by Django 2.0.2 on 2018-03-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCESS_NODE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ACCESS_SWITCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ports_count', models.IntegerField(default=0)),
                ('ports_types', models.CharField(blank=True, max_length=100)),
                ('u_vlans', models.CharField(blank=True, max_length=500)),
                ('t_vlans', models.CharField(blank=True, max_length=500)),
                ('access_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.ACCESS_NODE')),
            ],
        ),
        migrations.CreateModel(
            name='CAMPUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IP_ADDRESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IPOE_SERVICESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_ports', models.IntegerField(default=0)),
                ('c_vlan', models.IntegerField(default=0)),
                ('access_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.ACCESS_SWITCH')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.CLIENTS')),
            ],
        ),
        migrations.CreateModel(
            name='SUBNET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=15)),
                ('mask', models.IntegerField(default=28)),
                ('hostmin', models.CharField(max_length=15)),
                ('hosmax', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SW_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('fw_version', models.CharField(max_length=100)),
                ('hw_version', models.CharField(max_length=100)),
                ('ports_count', models.IntegerField(default=0)),
                ('ports_types', models.CharField(blank=True, max_length=100)),
                ('cfg_template', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='THREAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('outvlan', models.IntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.CAMPUS')),
            ],
        ),
        migrations.RenameField(
            model_name='mgs',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='mgs',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='mgs',
            name='lag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
        migrations.AddField(
            model_name='ip_address',
            name='net',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.SUBNET'),
        ),
        migrations.AddField(
            model_name='campus',
            name='mgs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MGS'),
        ),
        migrations.AddField(
            model_name='access_switch',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.IP_ADDRESS'),
        ),
        migrations.AddField(
            model_name='access_switch',
            name='sw_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.SW_MODEL'),
        ),
        migrations.AddField(
            model_name='access_node',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
    ]
