# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_squashed_0082_auto_20180725_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_node',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='access_node',
            unique_together=set([('address', 'thread')]),
        ),
    ]
