# Generated by Django 2.0.2 on 2018-02-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMPUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('mgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MGS')),
            ],
        ),
    ]
