# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20180727_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgs',
            name='campuses',
            field=models.IntegerField(default=0, help_text='Значение обновляется автоматически при вызове метода campus_count()', verbose_name='Количество кампусов в МГС'),
        ),
        migrations.AddField(
            model_name='mgs',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления данных по МГС'),
        ),
    ]
