# Generated by Django 2.0.2 on 2018-02-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=15)),
                ('mask', models.IntegerField(default=28)),
                ('HostMin', models.CharField(max_length=15)),
                ('HosMax', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='THREAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titile', models.CharField(max_length=20)),
                ('OutVlan', models.IntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.CAMPUS')),
            ],
        ),
        migrations.AddField(
            model_name='sub_net',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
    ]
