# Generated by Django 2.0.2 on 2018-03-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20180303_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='L2_SERVICESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpls', models.IntegerField(unique=True)),
                ('c_ports', models.IntegerField(default=0)),
                ('c_vlan', models.IntegerField(default=0)),
                ('access_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.ACCESS_SWITCH')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.CLIENTS')),
            ],
        ),
        migrations.CreateModel(
            name='LAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('s_vlan', models.IntegerField(default=0)),
                ('c_vlan', models.IntegerField(default=0)),
                ('lag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.LAG')),
            ],
        ),
        migrations.CreateModel(
            name='SHG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vpls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.L2_SERVICESS')),
            ],
        ),
        migrations.RemoveField(
            model_name='ipoe_servicess',
            name='access_switch',
        ),
        migrations.RemoveField(
            model_name='ipoe_servicess',
            name='c_ports',
        ),
        migrations.RemoveField(
            model_name='ipoe_servicess',
            name='c_vlan',
        ),
        migrations.AlterField(
            model_name='mgs',
            name='lag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.LAG'),
        ),
        migrations.AddField(
            model_name='ipoe_servicess',
            name='sap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.SAP'),
        ),
    ]
