# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20180730_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mgs',
            old_name='campuses',
            new_name='campuss',
        ),
    ]
