# Generated by Django 2.0.2 on 2018-02-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20180212_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub_net',
            new_name='SUBNET',
        ),
    ]
