# Generated by Django 2.0.2 on 2018-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20180305_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l2_servicess',
            name='access_switch',
        ),
        migrations.RemoveField(
            model_name='l2_servicess',
            name='c_ports',
        ),
        migrations.RemoveField(
            model_name='l2_servicess',
            name='c_vlan',
        ),
        migrations.AddField(
            model_name='l2_servicess',
            name='sap',
            field=models.ManyToManyField(to='network.SAP'),
        ),
    ]
