# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20180730_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgs',
            name='nodes',
            field=models.IntegerField(default=0, help_text='Значение обновляется автоматически при вызове метода campus_count()', verbose_name='Количество узлов в МГС'),
        ),
        migrations.AddField(
            model_name='mgs',
            name='switches',
            field=models.IntegerField(default=0, help_text='Значение обновляется автоматически при вызове метода campus_count()', verbose_name='Количество коммутаторов в МГС'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='last_update',
            field=models.DateTimeField(verbose_name='Время последнего обновления данных по МГС'),
        ),
    ]
