# Generated by Django 2.0.2 on 2018-03-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20180305_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipoe_servicess',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.CLIENTS'),
        ),
        migrations.AlterField(
            model_name='l2_servicess',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.CLIENTS'),
        ),
        migrations.DeleteModel(
            name='CLIENTS',
        ),
    ]
