# Generated by Django 2.0.2 on 2018-02-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20180212_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='Titile',
            new_name='Title',
        ),
    ]
