# Generated by Django 2.0.2 on 2018-03-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20180305_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipoe_servicess',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ipoe_servicess',
            name='sap',
        ),
        migrations.DeleteModel(
            name='IPOE_SERVICESS',
        ),
    ]
