# Generated by Django 2.0.2 on 2018-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20180212_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='AggInterface',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='thread',
            name='Kommutation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
