# Generated by Django 2.0.2 on 2018-03-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20180305_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l2_servicess',
            name='client',
        ),
        migrations.RemoveField(
            model_name='l2_servicess',
            name='sap',
        ),
        migrations.RemoveField(
            model_name='shg',
            name='vpls',
        ),
        migrations.DeleteModel(
            name='L2_SERVICESS',
        ),
        migrations.DeleteModel(
            name='SHG',
        ),
    ]
