# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20180730_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время последнего обновления данных по МГС'),
        ),
        migrations.AddField(
            model_name='campus',
            name='node_counter',
            field=models.IntegerField(default=0, editable=False, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество узлов в кампусе'),
        ),
        migrations.AddField(
            model_name='campus',
            name='switche_counter',
            field=models.IntegerField(default=0, editable=False, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество коммутаторов в кампусе'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='campus_counter',
            field=models.IntegerField(default=0, editable=False, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество кампусов в МГС'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='last_update',
            field=models.DateTimeField(editable=False, verbose_name='Время последнего обновления данных по МГС'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='node_counter',
            field=models.IntegerField(default=0, editable=False, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество узлов в МГС'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='switche_counter',
            field=models.IntegerField(default=0, editable=False, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество коммутаторов в МГС'),
        ),
    ]
