# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20180730_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего обновления данных по МГС'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время последнего обновления данных по МГС'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='cfg_template',
            field=models.FileField(upload_to='cfg_templates'),
        ),
    ]
