# Generated by Django 2.0.2 on 2018-03-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20180305_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('vid', models.IntegerField(primary_key=True, serialize=False, verbose_name='vlan')),
            ],
        ),
    ]
