# Generated by Django 2.0.2 on 2018-03-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sap',
            name='s_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.VLAN'),
        ),
    ]
