# Generated by Django 2.0.2 on 2018-03-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20180309_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sap',
            name='s_vlan',
            field=models.IntegerField(default=0),
        ),
    ]
