# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20180731_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_switch',
            name='network',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.SUBNET'),
        ),
    ]
