# Generated by Django 2.0.2 on 2018-03-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20180309_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sap',
            name='c_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvlan', to='network.VLAN'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='s_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='svlan', to='network.VLAN'),
        ),
    ]
