# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_access_switch_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_type',
            name='connection_type',
            field=models.IntegerField(default=0, verbose_name='Тип подключения.'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
