# Generated by Django 2.0.2 on 2018-03-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20180309_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Кампус', 'verbose_name_plural': 'Кампусы'},
        ),
        migrations.AlterModelOptions(
            name='mgs',
            options={'verbose_name': 'МГС', 'verbose_name_plural': 'МГС'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Нитка', 'verbose_name_plural': 'Нитки'},
        ),
        migrations.AlterModelOptions(
            name='vlan',
            options={'verbose_name': 'vlan'},
        ),
        migrations.AlterField(
            model_name='thread',
            name='outvlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.VLAN'),
        ),
    ]
