# Generated by Django 2.0.2 on 2018-03-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20180309_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnet',
            options={'verbose_name': 'Подсеть', 'verbose_name_plural': 'Подсети'},
        ),
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
