# Generated by Django 2.0.2 on 2018-03-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20180309_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_address',
            name='net',
        ),
        migrations.AddField(
            model_name='access_switch',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.SUBNET'),
        ),
        migrations.AlterField(
            model_name='access_switch',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='hosmax',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='hostmin',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.DeleteModel(
            name='IP_ADDRESS',
        ),
    ]
