# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20180804_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_switch',
            name='stp_root',
            field=models.BooleanField(default=False, verbose_name='STP_ROOT'),
        ),
    ]
