# Generated by Django 2.0.2 on 2018-03-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20180309_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='VENDORS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Вендор',
                'verbose_name_plural': 'Вендоры',
            },
        ),
        migrations.AlterModelOptions(
            name='access_node',
            options={'verbose_name': 'Узел доступа', 'verbose_name_plural': 'Узлы доступа'},
        ),
        migrations.AlterModelOptions(
            name='sw_model',
            options={'verbose_name': 'Модель коммутаторов', 'verbose_name_plural': 'Модели коммутаторов'},
        ),
    ]
