# Generated by Django 2.0.2 on 2018-03-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20180309_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sw_model',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.VENDORS'),
        ),
    ]
