# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20180805_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_switch',
            name='mac',
            field=models.CharField(blank=True, max_length=17, verbose_name='mac-адрес коммутатора'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='campus_counter',
            field=models.IntegerField(default=0, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество кампусов в МГС'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='node_counter',
            field=models.IntegerField(default=0, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество узлов в МГС'),
        ),
        migrations.AlterField(
            model_name='mgs',
            name='switche_counter',
            field=models.IntegerField(default=0, help_text='Значение обновляется автоматически при вызове метода update_counts()', verbose_name='Количество коммутаторов в МГС'),
        ),
    ]
