# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20180828_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_switch',
            name='sn',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серийный номер коммутатора'),
        ),
    ]
