# Generated by Django 2.0.2 on 2018-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20180309_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access_switch',
            options={'verbose_name': 'Коммутатор доступа', 'verbose_name_plural': 'Коммутаторы доступа'},
        ),
        migrations.AlterField(
            model_name='access_switch',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='fw_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='hw_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
