# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_access_switch_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_switch',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='ip-адрес'),
        ),
        migrations.AlterField(
            model_name='access_switch',
            name='mac',
            field=models.CharField(blank=True, max_length=17, verbose_name='mac-адрес'),
        ),
        migrations.AlterField(
            model_name='access_switch',
            name='sn',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='cfg_template',
            field=models.FileField(upload_to='cfg_templates', verbose_name='Шаблон конфигурации'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='fw_file',
            field=models.FileField(upload_to='fw', verbose_name='Файл прошивки'),
        ),
    ]
