# Generated by Django 2.0.2 on 2018-03-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20180309_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='mapvlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapvlan', to='network.VLAN'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='outvlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outvlan', to='network.VLAN'),
        ),
    ]
