# Generated by Django 2.0.2 on 2018-03-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20180309_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['title'], 'verbose_name': 'Кампус', 'verbose_name_plural': 'Кампусы'},
        ),
    ]
