# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20180828_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='sw_model',
            name='botrom_file',
            field=models.FileField(blank=True, upload_to='fw', verbose_name='Файл прошивки bootrom'),
        ),
        migrations.AddField(
            model_name='sw_model',
            name='transit_fw',
            field=models.FileField(blank=True, upload_to='fw', verbose_name='Файл промежуточной прошивки'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='fw_file',
            field=models.FileField(blank=True, upload_to='fw', verbose_name='Файл прошивки'),
        ),
    ]
