# Generated by Django 2.0.2 on 2018-03-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20180309_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='num_in_campus',
            field=models.IntegerField(default=1),
        ),
    ]
