# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20180903_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sw_model',
            name='ports_names',
            field=models.CharField(blank=True, max_length=700, verbose_name='Названия портов в конфиге'),
        ),
    ]
