# Generated by Django 2.0.2 on 2018-03-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_thread_num_in_campus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('campus', 'num_in_campus')},
        ),
    ]
