# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20180924_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='vlans',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
