# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_thread_vlans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mgs',
            options={'ordering': ['mgs_num'], 'verbose_name': 'МГС', 'verbose_name_plural': 'МГС'},
        ),
        migrations.AlterField(
            model_name='port_of_access_switch',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
