# Generated by Django 2.0.2 on 2018-03-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_mgs_mgs_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
