# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-03 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0024_historicalport_of_access_switch_historicalsw_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalACCESS_SWITCH',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, protocol='IPv4', verbose_name='ip-адрес')),
                ('stp_root', models.BooleanField(default=False, verbose_name='STP_ROOT')),
                ('mac', models.CharField(blank=True, max_length=17, verbose_name='mac-адрес')),
                ('sn', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('cfg_file', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('access_node', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='network.ACCESS_NODE')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='network.SUBNET')),
                ('sw_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='network.SW_MODEL')),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Коммутатор доступа',
                'ordering': ('-history_date', '-history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
