# Generated by Django 2.0.2 on 2018-03-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20180323_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_in_mgs', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Магистраль',
                'verbose_name_plural': 'Магистрали',
            },
        ),
        migrations.RemoveField(
            model_name='mgs',
            name='title',
        ),
        migrations.AddField(
            model_name='ms',
            name='mgs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MGS', verbose_name='Магистраль'),
        ),
        migrations.AlterUniqueTogether(
            name='ms',
            unique_together={('mgs', 'num_in_mgs')},
        ),
    ]
