# Generated by Django 2.0.2 on 2018-03-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_auto_20180323_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='ms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MS', verbose_name='МС'),
        ),
    ]
