# Generated by Django 2.0.2 on 2018-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_auto_20180323_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['ms', 'num_in_ms'], 'verbose_name': 'Кампус', 'verbose_name_plural': 'Кампусы'},
        ),
        migrations.AddField(
            model_name='campus',
            name='num_in_ms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('ms', 'num_in_ms')},
        ),
    ]
