# Generated by Django 2.0.2 on 2018-03-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_auto_20180323_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='prefix',
            field=models.CharField(choices=[('ppk', 'ППК'), ('mku', 'МКУ')], default='ppk', max_length=20, verbose_name='Название'),
        ),
    ]
