# Generated by Django 2.0.2 on 2018-03-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_auto_20180325_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms',
            name='mgs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MGS', verbose_name='МГС'),
        ),
    ]
