# Generated by Django 2.0.2 on 2018-03-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_auto_20180325_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnet',
            name='hosmax',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='hostmin',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='mask',
        ),
        migrations.AlterField(
            model_name='campus',
            name='prefix',
            field=models.CharField(choices=[('ppk', 'ППК'), ('mku', 'МКУ')], default='ppk', max_length=20, verbose_name='Префикс'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='num_in_mgs',
            field=models.IntegerField(default=1, verbose_name='Номер магистрали в МГС'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.THREAD'),
        ),
    ]
