# Generated by Django 2.0.2 on 2018-03-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_auto_20180326_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.CharField(max_length=18),
        ),
    ]
