# Generated by Django 2.0.2 on 2018-04-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_auto_20180326_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='GUTS_NETWORK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['campus', 'num_in_campus'], 'verbose_name': 'Нитка', 'verbose_name_plural': 'Нитки'},
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
    ]
