# Generated by Django 2.0.2 on 2018-04-05 07:01

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_auto_20180404_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guts_network',
            options={'ordering': ['description'], 'verbose_name': 'Подсеть', 'verbose_name_plural': 'Подсети разрешонные в ГУТС.'},
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='subnet',
        ),
        migrations.AlterField(
            model_name='access_node',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='guts_network',
            name='network',
            field=models.CharField(max_length=18, unique=True, validators=[network.models.validator_net_addr]),
        ),
    ]
