# Generated by Django 2.0.2 on 2018-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_auto_20180406_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='PORT_TYPE',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='0-upstream, 1-brn, 20-signal, 21-ktv-reciver, 50-pppoe, 51-ipoe, 52-wifi_hotspot, 53-wifi_p2p, 99-bad', max_length=200, verbose_name='Описание типа порта')),
                ('default_description', models.CharField(blank=True, max_length=200, verbose_name='Название порта поумолчанию')),
            ],
        ),
    ]
