# Generated by Django 2.0.2 on 2018-04-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0040_auto_20180414_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port_type',
            options={'verbose_name': 'Тип порта', 'verbose_name_plural': 'Типы портов'},
        ),
        migrations.AlterField(
            model_name='port_type',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
