# Generated by Django 2.0.2 on 2018-04-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0046_auto_20180415_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_type',
            name='is_bad',
            field=models.BooleanField(default=False),
        ),
    ]
