# Generated by Django 2.0.2 on 2018-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0047_port_type_is_bad'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_of_access_switch',
            name='is_bad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='is_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='is_upstream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='non_pppoe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, help_text='0-Upstream, 1-Branch, 20-Signal, 21-KTV-приемник, 50-PPPoE-клиент, 51-IPoE-клиент, 52-WiFi-HotSpot, 53-WiFi-P2P, 99-Неисправный порт', max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
