# Generated by Django 2.0.2 on 2018-04-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0049_auto_20180415_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_switch',
            name='ports_count',
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='ports_descriptions',
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='ports_types',
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='t_vlans',
        ),
        migrations.RemoveField(
            model_name='access_switch',
            name='u_vlans',
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, help_text='0-Upstream, 1-Branch, 20-Signal, 21-KTV-приемник, 50-PPPoE-клиент, 51-IPoE-клиент, 52-WiFi-HotSpot, 53-WiFi-P2P, 99-Неисправный порт, 100-Особый порт', max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
