# Generated by Django 2.0.2 on 2018-04-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0052_auto_20180415_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port_of_access_switch',
            name='type',
        ),
    ]
