# Generated by Django 2.0.2 on 2018-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0053_remove_port_of_access_switch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_of_access_switch',
            name='num_in_switch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='port_of_access_switch',
            unique_together={('access_switch', 'num_in_switch')},
        ),
    ]
