# Generated by Django 2.0.2 on 2018-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0054_auto_20180415_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_of_access_switch',
            name='is_bad',
            field=models.BooleanField(default=False, verbose_name='Нерабочий'),
        ),
    ]
