# Generated by Django 2.0.2 on 2018-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0055_auto_20180415_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sw_model',
            name='ports_names',
            field=models.CharField(blank=True, max_length=200, verbose_name='Названия портов в конфиге'),
        ),
    ]
