# Generated by Django 2.0.2 on 2018-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0057_auto_20180605_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_of_access_switch',
            name='port_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
