# Generated by Django 2.0.2 on 2018-06-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0058_port_of_access_switch_port_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port_type',
            name='is_bad',
        ),
        migrations.RemoveField(
            model_name='port_type',
            name='is_signal',
        ),
        migrations.RemoveField(
            model_name='port_type',
            name='is_upstream',
        ),
        migrations.RemoveField(
            model_name='port_type',
            name='non_pppoe',
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, help_text='0-Uplink, 1-Branch, 20-Signal, 21-KTV-приемник, 50-PPPoE-клиент, 51-IPoE-клиент, 52-WiFi-HotSpot, 53-WiFi-P2P, 99-Неисправный порт, 100-Особый порт', max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
