# Generated by Django 2.0.2 on 2018-06-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0059_auto_20180607_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port_of_access_switch',
            name='is_bad',
        ),
        migrations.RemoveField(
            model_name='port_of_access_switch',
            name='is_signal',
        ),
        migrations.RemoveField(
            model_name='port_of_access_switch',
            name='is_upstream',
        ),
        migrations.RemoveField(
            model_name='port_of_access_switch',
            name='non_pppoe',
        ),
        migrations.AddField(
            model_name='port_of_access_switch',
            name='port_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.PORT_TYPE'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, help_text='0-Магистральный порт, 1-Распределительный порт, 3-Абонентский порт (PPPoE-клиент), 4-Абонентский порт (прочие-подключения), 5-Сигнализатор, 99-Неисправный порт', max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
