# Generated by Django 2.0.2 on 2018-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0062_auto_20180614_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_type',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет типа порта.'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
