# Generated by Django 2.0.2 on 2018-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0063_auto_20180614_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sap',
            name='c_vlan',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='sap',
            name='s_vlan',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, help_text='0-Магистральный порт, 1-Распределительный порт, 3-PPPoE-подключение, 4-Прочее-подключение, 5-Сигнализатор, 99-Неисправный порт', max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
