# Generated by Django 2.0.2 on 2018-06-19 14:24

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0064_auto_20180619_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sap',
            options={'ordering': ['lag', 's_vlan', 'c_vlan']},
        ),
        migrations.AlterField(
            model_name='sap',
            name='c_vlan',
            field=models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='CVID'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='s_vlan',
            field=models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='SVID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='outvlan',
            field=models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='Внешний vlan'),
        ),
        migrations.AlterUniqueTogether(
            name='sap',
            unique_together={('lag', 's_vlan', 'c_vlan')},
        ),
    ]
