# Generated by Django 2.0.2 on 2018-06-19 14:27

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0065_auto_20180619_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='mapvlan',
            field=models.IntegerField(default=1, validators=[network.models.validator_vid], verbose_name='Внешний vlan'),
        ),
    ]
