# Generated by Django 2.0.2 on 2018-06-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0067_auto_20180619_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VLAN',
        ),
    ]
