# Generated by Django 2.0.2 on 2018-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0068_delete_vlan'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_switch',
            name='gw',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
        ),
    ]
