# Generated by Django 2.0.2 on 2018-06-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0069_access_switch_gw'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_switch',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.SUBNET'),
        ),
    ]
