# Generated by Django 2.0.2 on 2018-06-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0070_access_switch_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_switch',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.SUBNET'),
        ),
    ]
