# Generated by Django 2.0.2 on 2018-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0071_auto_20180622_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_switch',
            name='gw',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
