# Generated by Django 2.0.2 on 2018-06-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0072_auto_20180622_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_switch',
            name='gw',
        ),
        migrations.AddField(
            model_name='subnet',
            name='gw',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
        ),
    ]
