# Generated by Django 2.0.2 on 2018-06-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0073_auto_20180622_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD'),
        ),
    ]
