# Generated by Django 2.0.2 on 2018-06-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0074_auto_20180622_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='gw',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4', verbose_name='Адрес шлюза'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.CharField(max_length=18, unique=True, verbose_name='Подсеть'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.THREAD', verbose_name='Нитка'),
        ),
    ]
