# Generated by Django 2.0.2 on 2018-06-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0075_auto_20180623_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_switch',
            name='subnet',
        ),
    ]
