# Generated by Django 2.0.2 on 2018-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0076_remove_access_switch_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sw_model',
            name='fw_file',
            field=models.CharField(blank=True, max_length=100, verbose_name='Файл прошивки'),
        ),
    ]
