# Generated by Django 2.0.2 on 2018-07-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0077_sw_model_fw_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sw_model',
            name='fw_update_commands',
            field=models.TextField(blank=True, verbose_name='описание процесса обновления прошивки'),
        ),
    ]
