# Generated by Django 2.0.2 on 2018-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0078_sw_model_fw_update_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_switch',
            name='cfg_file',
            field=models.CharField(blank=True, help_text='Значение поля очищается при каждых изменениях коммутатора', max_length=200, verbose_name='Файл текущей конфигурации.'),
        ),
        migrations.AddField(
            model_name='sw_model',
            name='cfg_download_commands',
            field=models.TextField(blank=True, verbose_name='Описание процесса загрузки конфигурации'),
        ),
        migrations.AlterField(
            model_name='sw_model',
            name='fw_update_commands',
            field=models.TextField(blank=True, verbose_name='Описание процесса обновления прошивки'),
        ),
    ]
