# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0080_sw_model_eqm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sw_model',
            name='ports_types',
            field=models.CharField(blank=True, max_length=200, verbose_name='Типы портов по умолчанию'),
        ),
    ]
