# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

#    replaces = [('ipoe', '0001_initial'), ('ipoe', '0002_auto_20180725_1735')]

    initial = True

    dependencies = [
        ('network', '0001_squashed_0082_auto_20180725_1706'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOE_SERVICESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.CLIENTS')),
                ('sap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.SAP')),
            ],
            options={
                'verbose_name_plural': 'Услуги IPoE',
                'ordering': ['client', 'sap'],
                'verbose_name': 'Услуга IPoE',
            },
        ),
    ]
